// Code generated by bpf2go; DO NOT EDIT.
//go:build linux

package processdiscoveryreceiver

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadLifecycle returns the embedded CollectionSpec for lifecycle.
func loadLifecycle() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LifecycleBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lifecycle: %w", err)
	}

	return spec, err
}

// loadLifecycleObjects loads lifecycle and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lifecycleObjects
//	*lifecyclePrograms
//	*lifecycleMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLifecycleObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLifecycle()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lifecycleSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lifecycleSpecs struct {
	lifecycleProgramSpecs
	lifecycleMapSpecs
}

// lifecycleSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lifecycleProgramSpecs struct {
	TracepointSchedProcessExec *ebpf.ProgramSpec `ebpf:"tracepoint__sched_process_exec"`
	TracepointSchedProcessExit *ebpf.ProgramSpec `ebpf:"tracepoint__sched_process_exit"`
}

// lifecycleMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lifecycleMapSpecs struct {
	ProcessLifecycle *ebpf.MapSpec `ebpf:"process_lifecycle"`
}

// lifecycleObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLifecycleObjects or ebpf.CollectionSpec.LoadAndAssign.
type lifecycleObjects struct {
	lifecyclePrograms
	lifecycleMaps
}

func (o *lifecycleObjects) Close() error {
	return _LifecycleClose(
		&o.lifecyclePrograms,
		&o.lifecycleMaps,
	)
}

// lifecycleMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLifecycleObjects or ebpf.CollectionSpec.LoadAndAssign.
type lifecycleMaps struct {
	ProcessLifecycle *ebpf.Map `ebpf:"process_lifecycle"`
}

func (m *lifecycleMaps) Close() error {
	return _LifecycleClose(
		m.ProcessLifecycle,
	)
}

// lifecyclePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLifecycleObjects or ebpf.CollectionSpec.LoadAndAssign.
type lifecyclePrograms struct {
	TracepointSchedProcessExec *ebpf.Program `ebpf:"tracepoint__sched_process_exec"`
	TracepointSchedProcessExit *ebpf.Program `ebpf:"tracepoint__sched_process_exit"`
}

func (p *lifecyclePrograms) Close() error {
	return _LifecycleClose(
		p.TracepointSchedProcessExec,
		p.TracepointSchedProcessExit,
	)
}

func _LifecycleClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lifecycle_x86_bpfel.o
var _LifecycleBytes []byte
