version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
      # Times are staggered by 30m to spread load
      time: '02:00'
      timezone: US/Pacific
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
      time: '02:30'
      timezone: US/Pacific
