// Minimal vmlinux.h — only the typedefs needed by lifecycle.bpf.c.
// The lifecycle BPF programs do not access kernel struct fields so
// a full vmlinux.h generated by bpftool is not required.

#ifndef __VMLINUX_H__
#define __VMLINUX_H__

typedef unsigned char __u8;
typedef unsigned short __u16;
typedef unsigned int __u32;
typedef unsigned long long __u64;
typedef signed char __s8;
typedef signed short __s16;
typedef signed int __s32;
typedef signed long long __s64;

typedef __u16 u16;
typedef __u32 u32;
typedef __u64 u64;
typedef __s32 s32;

enum bpf_map_type {
	BPF_MAP_TYPE_UNSPEC = 0,
	BPF_MAP_TYPE_HASH = 1,
	BPF_MAP_TYPE_ARRAY = 2,
	BPF_MAP_TYPE_RINGBUF = 27,
};

#endif /* __VMLINUX_H__ */
