// Code generated by mdatagen. DO NOT EDIT.

package observek8sattributesprocessor

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("observek8sattributes")
)

const (
	TracesStability  = component.StabilityLevelBeta
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
)
