# This is an example config file for Observe-Agent
# Please download the config from Connections Portal

# Observe data token
# token: "${OBSERVE_TOKEN}"

# Target Observe collection url
# observe_url: "${OBSERVE_COLLECTION_ENDPOINT}"

host_monitoring:
  enabled: true
  logs: 
    enabled: true
  metrics:
    enabled: true

# otel_config_overrides:
#   exporters:
#     debug:
#       verbosity: detailed
#       sampling_initial: 5
#       sampling_thereafter: 200
#   service:
#     pipelines:
#       # This will override the existing metrics/host_monitoring pipeline and output to stdout debug instead
#       metrics/host_monitoring:
#         receivers: [hostmetrics/host-monitoring]
#         processors: [memory_limiter]
#         exporters: [debug]
