receivers:
  hostmetrics/host-monitoring-host:
    collection_interval: 60s
    root_path: /hostfs
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.frequency:
            enabled: true
          system.cpu.logical.count:
            enabled: true
          system.cpu.physical.count:
            enabled: true
      load:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
          system.linux.memory.available:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      network:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      processes:

service:
  pipelines:
    metrics/host_monitoring_host:
      receivers: [hostmetrics/host-monitoring-host]
      processors: [memory_limiter, resourcedetection, resourcedetection/cloud, batch]
      exporters: [prometheusremotewrite/observe]
