name: Release Version

on:
  push:
    # run only against tags
    tags:
      - "*"
      # Ignore nightly/dev tags
      - "!nightly*"
      - "!dev*"

permissions:
  id-token: write
  contents: write

jobs:
  vuln-check:
    name: Docker Image Vulnerability Check
    uses: ./.github/workflows/vuln-check.yaml
    secrets: inherit
    with:
      branch: ${{ github.ref }}

  goreleaser:
    needs: vuln-check
    runs-on: ubuntu-observe-agent-8cpu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.7

      - name: Install qemu
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GORELEASER_IAM_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          # 'latest', 'nightly', or a semver
          version: 2.7.0
          args: release --clean --skip=validate --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
