name: Release Nightly Version

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to create nightly release based on"
        required: true
        default: "main"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install msitools
        run: sudo apt-get install -y wixl
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Install qemu
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser-pro
          # 'latest', 'nightly', or a semver
          version: nightly
          args: release --clean --skip=validate --verbose --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
