name: Release Nightly Version

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to create nightly release based on"
        required: true
        default: "main"

permissions:
  id-token: write
  contents: write

jobs:
  goreleaser:
    if: contains('["obs-gh-alexlew", "obs-gh-mattcotter", "obs-gh-enricogiorio"]', github.actor)
    runs-on: ubuntu-observe-agent-8cpu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.7

      - name: Install msitools
        run: sudo apt-get install -y wixl

      - name: Install qemu
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GORELEASER_IAM_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: 2.4.4
          args: release --clean --skip=validate --verbose --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
