name: Run Go tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to attempt to build"
        required: true
        default: "main"

jobs:
  test:
    strategy:
      matrix:
        go: [1.24.6]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
      - name: Test
        run: make go-test
