name: Docker Image Vulnerability Check

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  TEST_TAG: observeinc/observe-agent:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.12

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser-pro
          # 'latest', 'nightly', or a semver
          version: 2.4.4
          args: build --snapshot --id=default
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Copy Binary
        run: |
          cp dist/default_linux_386/observe-agent .

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.TEST_TAG }}
          outputs: type=docker,dest=${{ runner.temp }}/myimage.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: ${{ runner.temp }}/myimage.tar
  
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          image: ${{ env.TEST_TAG }}
          command: cves,recommendations
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
