name: Docker Image Vulnerability Check

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  TEST_TAG: observeinc/observe-agent:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.12

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: 2.4.4
          args: build --snapshot --id=default
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Copy Binary
        run: |
          cp dist/default_linux_386_sse2/observe-agent .
      
      - name: Print files
        run: ls

      - name: Build an image from Dockerfile
        run: docker build -f packaging/docker/Dockerfile -t docker.io/${{ env.TEST_TAG}} .

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          image: ${{ env.TEST_TAG }}
          command: cves,recommendations
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: false
          exit-code: true
